"""What the GP-150 skeleton writer puts into a patch is what the decoder reads
back (name, chain order, models, parameters, on/off) — on synthetic patches
generated by app/tests/gp150_corpus.py. This checks consistency of the writer and
decoder with each other; the byte-exact format is covered by the captures and by
the real corpus (GP150_CORPUS_DIR) in the other gp150 tests."""

import pytest

from app.tests import gp150_corpus as corpus
from patch import gp150_format as g


@pytest.fixture(scope="module")
def patches():
    return corpus.synthetic_patches()


def test_synthetic_set_is_varied(patches):
    assert len(patches) >= 40
    assert len({tuple(e["chain"]) for _, _, e in patches}) >= 10
    assert len({e["name"] for _, _, e in patches}) >= 30
    assert {len(e["name"]) for _, _, e in patches} >= {1, 13} or max(len(e["name"]) for _, _, e in patches) == 13


def test_decoder_reads_back_what_was_written(patches):
    for fname, prst, exp in patches:
        p = g.decode(prst)
        assert p.name == exp["name"], fname
        assert list(p.chain_order) == exp["chain"], fname
        for mod, fxid in exp["models"].items():
            assert p.module_models[mod] == fxid, (fname, mod)
        for mod, en in exp["enabled"].items():
            assert p.module_enabled[mod] is en, (fname, mod)
        for mod, params in exp["params"].items():
            for alg, val in params.items():
                assert g.read_module_param_by_alg_id(prst, mod, alg) == pytest.approx(val), (fname, mod, alg)


def test_untouched_bytes_stay_those_of_the_skeleton(patches):
    skeleton = corpus.skeleton_bytes()
    for fname, prst, _ in patches:
        assert len(prst) == len(skeleton)
        # header, constants and the tail outside any written field are never touched
        assert prst[:4] == skeleton[:4], fname
        assert prst[-200:] == skeleton[-200:], fname


def test_converted_upstream_presets_are_valid(patches):
    conv = corpus.converted_upstream_patches()
    assert len(conv) >= 3
    for fname, prst in conv:
        assert g.is_valid_order(prst), fname
        p = g.decode(prst)
        for mod, en in p.module_enabled.items():
            if en and mod != "VOL":
                assert p.module_models[mod] != g.FXID_NONE, (fname, mod)
