/*
 * Verifies nam_wavenet.js against REAL output from the official
 * `neural-amp-modeler` Python package (not a reimplementation compared to
 * itself) -- the strongest validation this project's own "verify by
 * round-trip against real data" discipline can ask for, short of a real
 * device capture (which doesn't apply here: NAM inference happens entirely
 * off-device, there's nothing to capture from the GP-150 itself).
 *
 * Fixtures (app/tests/fixtures/nam_wavenet_reference_{1,2}.json) were
 * generated by installing the real `neural-amp-modeler` PyPI package in a
 * throwaway venv, loading refs/A2.nam's "lite" submodel (the exact
 * architecture this project's own NAM upload path already targets --
 * NAM_WEIGHTS_COUNT=1871 in webmidi_gp150.js), and running its own
 * `model(x)` forward pass on two independent test signals (random noise,
 * and an impulse+burst mix). See nam_wavenet.js's own module docstring for
 * the exact architecture derivation (weight-count arithmetic, real
 * state_dict shapes).
 *
 *   node app/tests/test_nam_wavenet_js.mjs
 */
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../..");
const { NamWaveNet } = require(resolve(here, "../static/nam_wavenet.js"));

const a2 = JSON.parse(readFileSync(resolve(repoRoot, "refs/A2.nam"), "utf8"));
const { layerConfig, weights } = NamWaveNet.extractSingleArrayModel(a2);

let failures = 0;
function check(name, cond, detail) {
  if (cond) {
    console.log(`ok   ${name}`);
  } else {
    failures++;
    console.log(`FAIL ${name}${detail ? " — " + detail : ""}`);
  }
}

function maxAbsError(a, b) {
  let m = 0;
  for (let i = 0; i < a.length; i++) m = Math.max(m, Math.abs(a[i] - b[i]));
  return m;
}

for (const fixtureName of ["nam_wavenet_reference_1.json", "nam_wavenet_reference_2.json"]) {
  const ref = JSON.parse(readFileSync(resolve(here, "fixtures", fixtureName), "utf8"));
  const actual = NamWaveNet.namWaveNetForward(layerConfig, weights, ref.input);
  check(`${fixtureName}: output length matches input length`, actual.length === ref.input.length);
  const err = maxAbsError(actual, ref.output);
  // PyTorch computes in float32; this JS port uses float64 throughout, so a
  // small float32-rounding-level gap is expected, not a bug.
  check(`${fixtureName}: matches real PyTorch output to float32 precision`, err < 1e-5, `max abs error = ${err}`);
}

// "Classic" multi-layer-array schema (head_size/head_bias instead of a head
// dict) -- validated against the real neural-amp-modeler==0.8.4 package
// (the era this schema is from), using refs/wavenet_a1_standard.nam (2
// layer arrays, channels 16->8, Tanh). This exact code path was also
// validated live against a real user-supplied file (a third-party
// amp capture, not committed here) that the CURRENT
// neural-amp-modeler package (0.13.0) fails to even load -- see this
// module's own docstring.
{
  const classicNam = JSON.parse(readFileSync(resolve(repoRoot, "refs/wavenet_a1_standard.nam"), "utf8"));
  const model = NamWaveNet.extractClassicModel(classicNam);
  check("extractAnyModel detects the classic schema", NamWaveNet.extractAnyModel(classicNam).kind === "classic");

  const ref = JSON.parse(readFileSync(resolve(here, "fixtures", "nam_wavenet_classic_reference.json"), "utf8"));
  const actual = NamWaveNet.classicWaveNetForward(model.config, model.weights, ref.input_unpadded);
  check("classic schema: output length matches input length", actual.length === ref.input_unpadded.length);
  const err = maxAbsError(actual, ref.output);
  check("classic schema: matches real PyTorch (0.8.4) output to float32 precision", err < 1e-5, `max abs error = ${err}`);
}

// The small refs/wavenet.nam test file (2 tiny layer arrays, Tanh) turns
// out to ALSO be classic-schema -- a nice extra, independent validation
// case (different channel counts and receptive field than the other two).
{
  const tinyNam = JSON.parse(readFileSync(resolve(repoRoot, "refs/wavenet.nam"), "utf8"));
  const model = NamWaveNet.extractClassicModel(tinyNam);
  const ref = JSON.parse(readFileSync(resolve(here, "fixtures", "nam_wavenet_classic_tiny_reference.json"), "utf8"));
  const actual = NamWaveNet.classicWaveNetForward(model.config, model.weights, ref.input_unpadded);
  const err = maxAbsError(actual, ref.output);
  check("tiny classic-schema file matches real PyTorch (0.8.4) output", err < 1e-5, `max abs error = ${err}`);
}

// Refuses a known-unsupported feature (gated activation) rather than
// silently producing wrong output.
{
  const gatedConfig = {
    layers: [
      {
        input_size: 1,
        condition_size: 1,
        head_size: 1,
        channels: 2,
        kernel_size: 3,
        dilations: [1],
        activation: "Tanh",
        gated: true,
        head_bias: true,
      },
    ],
    head: null,
    head_scale: 0.02,
  };
  let threw = false;
  try {
    NamWaveNet.classicWaveNetForward(gatedConfig, new Array(100).fill(0), [0, 0, 0]);
  } catch (e) {
    threw = /gated/.test(e.message);
  }
  check("refuses a gated classic-schema config with a clear error", threw);
}

if (failures > 0) {
  console.error(`\n${failures} check(s) failed`);
  process.exit(1);
} else {
  console.log("\nall checks passed");
}
